# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmap_app', '0005_auto_20170405_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offering',
            name='description',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='offering',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
