# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodmap_app', '0006_auto_20170418_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferingTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('kosher', 'Kosher'), ('gluten-free', 'Gluten-Free'), ('peanut-free', 'Peanut-Free')], max_length=50)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodmap_app.Offering')),
            ],
        ),
    ]
