# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-06 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmap_app', '0007_offeringtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='recur',
            field=models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='offering',
            name='recur_end_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='offering',
            name='description',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
