#!/bin/bash
#
# setup
# Author: Michael Friedman
#
# Sets up your environment with the necessary dependencies to work on this
# project, and initializes the database. As more dependencies become required,
# update this script to install them.

# Validate usage
usage="usage: ./setup"
if [ $# -ne 0 ]; then
  echo $usage
  exit
fi

# Set up python virtual environment
if [ ! -d "venv" ]; then
  echo "Setting up Python virutal environment..."
  virtualenv venv

  # Arrange for 'activate' script in the virtual environment to also set
  # DJANGO_SETTINGS_MODULE and PROJECT_MODE environment variables. These tell
  # the Django project and the scraper whether to use development settings or
  # production settings. *Set to development settings by default.*
  cd venv/bin/
  echo 'export DJANGO_SETTINGS_MODULE="foodmap_proj.settings.development"' >> activate
  echo 'export PROJECT_MODE="development"' >> activate
  cd ../..

  echo "Done!"
  echo
fi
source venv/bin/activate

# Download dependencies
echo "Downloading dependencies..."
pip install Django==1.10.6
pip install Pillow==4.0.0
pip install selenium==3.3.1
echo "Done!"
echo

# Set up database
echo "Setting up database..."
python setup_database.py
echo "Done!"
echo

deactivate

echo "Remember to activate the Python virtual environment by running 'source venv/bin/activate' to use the installed dependencies. Run 'deactivate' to disable the environment when finished working."

