# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmap_app', '0003_auto_20170320_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='thread_id',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
        migrations.AlterField(
            model_name='location',
            name='lng',
            field=models.DecimalField(decimal_places=5, max_digits=9),
        ),
    ]
