#!/bin/bash
#
# test_setup_database_real
# Author: Michael Friedman
#
# Tests the setup_database.py script. This is temporary; it is based on the
# implementation of setup_database.py that prints the location entries to
# stderr, rather than actually enter them into the database. It just checks
# that the scraping procedure obtains the right information.

# Write expected output to a file
printf "1 lawrence drive\t|\t40.332\t|\t-74.656\n" >> __exp_out
printf "nassau hall\t|\t40.348\t|\t-74.659\n" >> __exp_out
printf "maclean house\t|\t40.349\t|\t-74.66\n" >> __exp_out
printf "stanhope hall\t|\t40.348\t|\t-74.66\n" >> __exp_out
printf "west college\t|\t40.347\t|\t-74.659\n" >> __exp_out

# Run script
python setup_database.py -p real 2> __test_out # for now, stderr has the output we want to test

# Compare
if ! diff -q __exp_out __test_out > /dev/null 2> /dev/null; then
  printf "FAILURE: Here is diff...\n"
  diff -y __exp_out __test_out
else
  printf "SUCCESS!\n"
fi
